name: checks

on: [push]

jobs:

  go:
    name: go checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.23.4'
          cache: true

      - run: make fmt
      - name: Verify no changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git diff
            echo "::error::go mod tidy or go fmt needs to be run and the results committed"
            exit 1
          fi
      - run: make check

